# Generated by Django 2.0.5 on 2018-06-05 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                help_text=
                'This represents the estimated time it takes to complete a task',
                null=True,
                verbose_name='Estimated Time'),
        ),
    ]
