# Generated by Django 2.0.6 on 2018-06-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                help_text='This represents the description of the Location.',
                verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(
                blank=True,
                default=None,
                help_text=
                'This represents the estimated time it takes to complete a task',
                null=True,
                verbose_name='Estimated Time'),
        ),
    ]
