# Generated by Django 2.0.5 on 2018-06-14 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='shapefile',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, help_text='This represents the Shapefile of the Location', null=True, srid=4326, verbose_name='Shapefile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='locations',
            field=models.ManyToManyField(blank=True, default=None, help_text='This represents the locations.', through='tasking.TaskLocation', to='tasking.Location', verbose_name='Locations'),
        ),
    ]
