# Generated by Django 2.0.5 on 2018-05-09 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0002_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(blank=True, default=None, help_text='This represents the tasklist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasking.TaskList', verbose_name='Task List'),
        ),
    ]
