# Generated by Django 2.0.5 on 2018-06-18 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0002_auto_20180605_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='shapefile',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                default=None,
                help_text='This represents the Shapefile of the Location',
                null=True,
                srid=4326,
                verbose_name='Shapefile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text='This is the date and time the task ends.',
                null=True,
                verbose_name='End'),
        ),
    ]
