# Generated by Django 2.0.5 on 2018-06-08 09:06

from django.db import migrations, models
import django.db.models.deletion
import tasking.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0002_auto_20180605_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLocation',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Created')),
                ('modified',
                 models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('timing_rule',
                 models.TextField(
                     help_text='This stores the rrule for recurrence.',
                     validators=[tasking.validators.validate_rrule],
                     verbose_name='Timing Rule')),
                ('start', models.TimeField(verbose_name='Start Time')),
                ('end', models.TimeField(verbose_name='End Time')),
                ('location',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='tasking.Location')),
            ],
            options={
                'ordering': ['task', 'location', 'start'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='locations',
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text='This represents the location.',
                through='tasking.TaskLocation',
                to='tasking.Location',
                verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='tasklocation',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='tasking.Task'),
        ),
    ]
