# Generated by Django 2.0.5 on 2018-06-14 13:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0002_auto_20180605_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='shapefile',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, help_text='This represents the Shapefile of the Location', null=True, srid=4326, verbose_name='Shapefile'),
        ),
    ]
