# Generated by Django 2.0.5 on 2018-06-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0003_auto_20180618_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Created')),
                ('modified',
                 models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name',
                 models.CharField(
                     help_text='This is the name of the Location Type',
                     max_length=255,
                     verbose_name='Name')),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='This represents the Location Type.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='tasking.LocationType',
                verbose_name='Location Type'),
        ),
    ]
