# Generated by Django 2.0.5 on 2018-05-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0003_task_tasklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasklist',
            new_name='task_list',
        ),
    ]
