# Generated by Django 2.0.5 on 2018-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0004_auto_20180509_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(blank=True, default=None, help_text='This represents the Task.', to='tasking.Task', verbose_name='Task'),
        ),
    ]
