# Generated by Django 2.0.5 on 2018-06-26 11:29

from django.db import migrations, models
import tasking.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tasking', '0004_auto_20180620_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timing_rule',
            field=models.TextField(
                blank=True,
                default=None,
                help_text='This stores the rrule for recurrence.',
                null=True,
                validators=[tasking.validators.validate_rrule],
                verbose_name='Timing Rule'),
        ),
    ]
