repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        exclude: migrations
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --rcfile=.pylintrc
        files: tasking
        exclude: migrations
        language: system
        types: [python]
